[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.5"
once_cell = "1.19.0"
regex = "1.10.6"

[[bin]]
name="ex6"
path="src/ex6.rs"

[[bin]]
name="ex7"
path="src/ex7.rs"
